#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6
SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "$SCRIPT_DIR/.." && pwd)
ENV_FILE="$REPO_ROOT/.env"
REMOTE_DIR=/opt/pgd-teletrabalho
cd "$REPO_ROOT"

corpus_cutoff() {
  grep -m1 '"corpus_cutoff"' "$REPO_ROOT/snapshot/manifest.json" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}'
}

banner "PGD Teletrabalho droplet"

stage "Create a Docker 1-Click Droplet"
say "DigitalOcean bills this VM. The image already has Docker Engine and Compose."
say "This repo is private, so we will copy files over SSH instead of git clone."
open_url "https://marketplace.digitalocean.com/apps/docker"
step "If you are not signed in, sign in to DigitalOcean."
step "Click the Deploy to DigitalOcean / Create Droplet button."
step "Choose a region close to you."
step "Choose a Basic plan with at least 4 GB RAM (2 vCPU / 4 GB is enough to build)."
step "Under Authentication, select an SSH key from this computer. Password login is not recommended."
note "No SSH key on the account? Add one at https://cloud.digitalocean.com/account/security then return to the create form."
step "Set the hostname to pgd-teletrabalho (or any name you will recognise)."
step "Do not add App Platform, Kubernetes, Spaces, or extra volumes."
step "If you attach a Cloud Firewall, allow TCP 22 and TCP 3000. The default 1-Click has 3000 open."
step "Click Create Droplet and wait until the public IPv4 address appears."
if ! confirm "Droplet created and showing a public IPv4?"; then
  say "Stopped. Re-run this wizard after the droplet exists."
  exit 0
fi

stage "Capture the public IPv4"
open_url "https://cloud.digitalocean.com/droplets"
step "Open the pgd-teletrabalho droplet."
step "Copy the public IPv4 address shown at the top of the droplet page."
ask DROPLET_IP "Paste the public IPv4:"
if [[ ! "$DROPLET_IP" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  warn "That does not look like an IPv4 address."
  exit 1
fi
write_env DROPLET_IP "$DROPLET_IP"

stage "Confirm SSH as root"
say "The Docker 1-Click image logs in as root with your SSH key."
step "This machine must already be able to ssh root@${DROPLET_IP} (the key you attached)."
pause "Press Enter to test SSH."
if ! ssh -o StrictHostKeyChecking=accept-new -o ConnectTimeout=15 "root@$DROPLET_IP" "docker compose version"; then
  warn "SSH or docker compose failed. Add your public key to the droplet and re-run."
  exit 1
fi
note "Docker Compose is installed on the droplet."

stage "OpenAI API key"
say "Ask uses this key for model-written answers. An empty value still indexes the snapshot and uses an extractive draft."
say "The key is written to .env on this machine and on the droplet. It is not baked into the image."
ask_secret OPENAI_API_KEY "Paste OPENAI_API_KEY (Enter keeps current / empty is allowed):"
write_env OPENAI_API_KEY "$OPENAI_API_KEY"

stage "Copy the repo and start Compose"
say "The droplet will run the same compose.yaml as local development."
say "Postgres and Ask bind to 127.0.0.1; only port 3000 is public."
note "Destination: root@${DROPLET_IP}:${REMOTE_DIR}"
if ! confirm "Copy this private repo and run docker compose up --build on the droplet?"; then
  SKIPPED+=("copy + docker compose up on ${DROPLET_IP}")
  finish
  exit 0
fi
CUTOFF=$(corpus_cutoff)
if [[ -z "$CUTOFF" ]]; then
  warn "Could not read corpus_cutoff from snapshot/manifest.json."
  exit 1
fi
ssh "root@$DROPLET_IP" "mkdir -p '$REMOTE_DIR'"
tar -C "$REPO_ROOT" \
  --exclude=.venv \
  --exclude=node_modules \
  --exclude=__pycache__ \
  --exclude=.pytest_cache \
  --exclude=.next \
  --exclude='*.egg-info' \
  -czf - \
  compose.yaml .dockerignore .env.example README.md CONTEXT.md api web snapshot \
  | ssh "root@$DROPLET_IP" "tar -xzf - -C '$REMOTE_DIR'"
{
  printf 'OPENAI_API_KEY=%s\n' "$OPENAI_API_KEY"
  printf 'EMBEDDING_MODEL=text-embedding-3-small\n'
  printf 'CHAT_MODEL=gpt-4o-mini\n'
  printf 'CORPUS_CUTOFF=%s\n' "$CUTOFF"
  printf 'WEB_ORIGIN=http://%s:3000\n' "$DROPLET_IP"
} | ssh "root@$DROPLET_IP" "cat > '$REMOTE_DIR/.env' && chmod 600 '$REMOTE_DIR/.env'"
note "Remote .env written (mode 600). Starting Compose — the first build can take several minutes."
ssh "root@$DROPLET_IP" "cd '$REMOTE_DIR' && docker compose up --build -d"

stage "Open Ask and check the Corpus Cutoff"
say "When Compose returns, the chat should be reachable without a second architecture."
HEALTH=$(ssh "root@$DROPLET_IP" "curl -sf http://127.0.0.1:8000/health" || true)
note "Ask /health: ${HEALTH:-unavailable}"
if [[ "$HEALTH" != *"$CUTOFF"* ]]; then
  warn "Corpus Cutoff from Ask did not match snapshot/manifest.json ($CUTOFF)."
  SKIPPED+=("confirm Corpus Cutoff on http://${DROPLET_IP}:3000")
fi
CURRENT=$(printf '%s' '{"question":"A participação no teletrabalho constitui direito adquirido?"}' \
  | ssh "root@$DROPLET_IP" 'curl -sf http://127.0.0.1:8000/ask -H "Content-Type: application/json" -d @-' || true)
REFUSAL=$(printf '%s' '{"question":"Qual a alíquota do IOF para investimento no exterior?"}' \
  | ssh "root@$DROPLET_IP" 'curl -sf http://127.0.0.1:8000/ask -H "Content-Type: application/json" -d @-' || true)
if [[ "$CURRENT" != *answered* ]] || [[ "$CURRENT" != *262/2025* ]]; then
  warn "Current Teletrabalho question did not return a checkable Citation to Resolução 262."
  SKIPPED+=("Current Citation on http://${DROPLET_IP}:3000")
fi
if [[ "$REFUSAL" != *insufficient_evidence* ]]; then
  warn "Out-of-snapshot question did not return Insufficient Evidence."
  SKIPPED+=("Insufficient Evidence on http://${DROPLET_IP}:3000")
fi
open_url "http://${DROPLET_IP}:3000"
step "Confirm Corte do corpus matches the snapshot, not today's gazette."
step "Click a Citation and check the PDF page."
pause "Press Enter after you have checked the chat."

finish
say "Chat: http://${DROPLET_IP}:3000"
note "No MinIO, Redis, or PDF upload was added. Destroy the droplet in the DigitalOcean UI when the demo is over."
